#!/usr/bin/env python3
"""Build the compact hot-context brief used to resume a learning session."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LEARNING = ROOT / "learning"
DEFAULT_COURSES = ROOT / "curriculum" / "COURSE_PRACTICE_MAP.csv"

STATE_FIELDS = [
    "Status",
    "Current phase",
    "Source root",
    "Commit",
    "MiniTorch root",
    "Last session",
    "Next action",
    "Active blockers",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--learning-dir", type=Path, default=DEFAULT_LEARNING)
    parser.add_argument("--course-map", type=Path, default=DEFAULT_COURSES)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="update NEXT_SESSION.md")
    mode.add_argument("--check", action="store_true", help="fail when NEXT_SESSION.md is stale")
    return parser.parse_args()


def state_fields(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    values: dict[str, str] = {}
    for key in STATE_FIELDS:
        match = re.search(rf"^- {re.escape(key)}:\s*(.+)$", text, re.M)
        if match is None:
            raise ValueError(f"STATE.md is missing '- {key}:'")
        values[key] = match.group(1).strip()
    return values


def calibrated_baseline(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    match = re.search(
        r"^## 2026-09-02 重新校准的起点.*?\n(.*?)(?=^## )", text, re.M | re.S
    )
    if match is None:
        raise ValueError("PROFILE.md is missing the calibrated-baseline section")
    return [
        line.removeprefix("- ").strip()
        for line in match.group(1).splitlines()
        if line.startswith("- ")
    ]


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def current_course(rows: list[dict[str, str]], phase: str) -> dict[str, str]:
    milestones = re.findall(r"\bM\d+(?:\.\d+)?[a-z]?\b", phase)
    for milestone in milestones:
        for row in rows:
            if row["milestone"] == milestone:
                return row
    raise ValueError(f"no course row matches current phase: {phase}")


def active_reviews(path: Path) -> list[str]:
    rows: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) != 9 or cells[0] == "Due policy":
            continue
        if cells[-1].startswith(("eligible", "due", "active")):
            rows.append(
                f"{cells[3]}.{cells[4]} — {cells[7]} (hint ceiling {cells[6]})"
            )
    return rows


def latest_note(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("|") and "[session note]" in line:
            match = re.search(r"\((sessions/[^)]+)\)", line)
            if match:
                return f"learning/notebook/{match.group(1)}"
    return "none"


def render(learning: Path, course_map: Path) -> str:
    state = state_fields(learning / "STATE.md")
    course = current_course(read_rows(course_map), state["Current phase"])
    concepts = [value for value in course["concept_ids"].split(";") if value]
    mastery = {
        row["concept_id"]: row
        for row in read_rows(learning / "MASTERY.csv")
        if row["concept_id"] in concepts
    }
    reviews = active_reviews(learning / "REVIEW_QUEUE.md")
    baseline = calibrated_baseline(learning / "PROFILE.md")

    lines = [
        "# Next learning session — generated hot context",
        "",
        "> Generated by `scripts/build_next_session.py`; edit its source files, not this file.",
        "",
        "## Resume contract",
        "",
    ]
    for key in STATE_FIELDS:
        lines.append(f"- {key}: {state[key]}")
    lines.extend(
        [
            f"- Latest completed notebook: `{latest_note(learning / 'notebook' / 'INDEX.md')}`",
            "",
            "## Current course slice",
            "",
            f"- Course: `{course['course_id']}` — {course['title']}",
            f"- Milestone/release: `{course['milestone']}` / `{course['release']}`",
            f"- Knowledge for this slice: {course['knowledge_block']}",
            f"- Immediate learner action: {course['immediate_learner_action']}",
            f"- Gate evidence: {course['runnable_evidence']}",
            "- Relevant mastery:",
        ]
    )
    for concept in concepts:
        row = mastery[concept]
        dimensions = ", ".join(
            f"{name}={row[name]}"
            for name in ["explain", "locate", "trace", "debug", "modify", "transfer", "retain"]
        )
        lines.append(f"  - `{concept}`: {row['status']}; {dimensions}")
    lines.extend(["", "## Calibrated learner baseline", ""])
    lines.extend(f"- {item}" for item in baseline)
    lines.extend(["", "## Eligible project-grounded reviews", ""])
    lines.extend(f"- {item}" for item in reviews)
    if not reviews:
        lines.append("- None; do not activate prerequisite-blocked reviews.")
    lines.extend(
        [
            "",
            "## Cold-context routing",
            "",
            "- Ordinary session: read only the current milestone section and the relevant teaching reference.",
            "- Milestone/scope change: read the accepted specs, full roadmap and coverage audit.",
            "- PrivateUse/compiler work: additionally read the matching backend/inference specification.",
            "- Assessment write: use one reviewed session manifest; load schema details only then.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    learning = args.learning_dir.resolve()
    course_map = args.course_map.resolve()
    output = learning / "NEXT_SESSION.md"
    try:
        expected = render(learning, course_map)
    except (OSError, KeyError, ValueError) as exc:
        print(f"Cannot build next-session brief: {exc}", file=sys.stderr)
        return 1
    if args.write:
        output.write_text(expected, encoding="utf-8")
        print(f"Updated {output}")
        return 0
    if args.check:
        actual = output.read_text(encoding="utf-8") if output.is_file() else ""
        if actual != expected:
            print(
                "NEXT_SESSION.md is stale; run scripts/build_next_session.py --write",
                file=sys.stderr,
            )
            return 1
        print("Next-session hot context is current.")
        return 0
    print(expected, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
